# Generated by Django 3.2.3 on 2021-05-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('balance_last_update', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('PERSONAL', 'Personal'), ('AGENT', 'Agent'), ('MERCHANT', 'Merchant')], max_length=17)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
