# Generated by Django 3.2.3 on 2021-05-24 20:24

from django.db import migrations
import random
import string

def insertReservedAccounts(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Account = apps.get_model("accounts", "Account")

    # Creating Dummy Accounts on Migration
    accounts_name = ['Charge', 'Card', 'TopUp', 'Earth Donation', 'Electricity Bill']
    
    for i in range(100):
        # generating uniuqe password
        passwrd = ''.join(random.choice(string.printable) for i in range(12))
        
        # add number 001, 002
        n = 3
        pad = '0'
        
        acc_name = accounts_name[i] if i < len(accounts_name) else 'Reserved'
        acc = Account(phone='01777777'+str(i).rjust(n, pad), name=acc_name, type='MERCHANT', password=passwrd)
                
        # if card add initial balance
        if  i < len(accounts_name) and accounts_name[i] == 'Card':
            acc.balance = 100000;
        acc.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insertReservedAccounts),
    ]
