# Generated by Django 3.2.3 on 2021-05-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('card_no', models.CharField(max_length=19, unique=True)),
                ('validity', models.CharField(max_length=255)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
    ]
